eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
      
      
# okta:
#   oauth2:
#     issuer: https://dev-12872364.okta.com/oauth2/default
#     audience: api://default
#     client-id: 0oao5mpbn9dGQzvTt5d7
#     client-secret: gjjN0HHOJogAlgfJg7O1eEDK1Denp9kX-0ZQ5vQrOIXBow7u8Nx8VJN_P5350_2J
#     scopes: openid, profile, email, offline_access, customer, admin

app:
 name: venkata rao ch
